// Code generated by go-swagger; DO NOT EDIT.

package identity_protection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// APIPreemptProxyGetPolicyRulesQueryReader is a Reader for the APIPreemptProxyGetPolicyRulesQuery structure.
type APIPreemptProxyGetPolicyRulesQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIPreemptProxyGetPolicyRulesQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIPreemptProxyGetPolicyRulesQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewAPIPreemptProxyGetPolicyRulesQueryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewAPIPreemptProxyGetPolicyRulesQueryTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAPIPreemptProxyGetPolicyRulesQueryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /identity-protection/queries/policy-rules/v1] api.preempt.proxy.get.policy-rules.query", response, response.Code())
	}
}

// NewAPIPreemptProxyGetPolicyRulesQueryOK creates a APIPreemptProxyGetPolicyRulesQueryOK with default headers values
func NewAPIPreemptProxyGetPolicyRulesQueryOK() *APIPreemptProxyGetPolicyRulesQueryOK {
	return &APIPreemptProxyGetPolicyRulesQueryOK{}
}

/*
APIPreemptProxyGetPolicyRulesQueryOK describes a response with status code 200, with default header values.

OK
*/
type APIPreemptProxyGetPolicyRulesQueryOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *APIPreemptProxyGetPolicyRulesQueryOKBody
}

// IsSuccess returns true when this api preempt proxy get policy rules query o k response has a 2xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api preempt proxy get policy rules query o k response has a 3xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy get policy rules query o k response has a 4xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api preempt proxy get policy rules query o k response has a 5xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy get policy rules query o k response a status code equal to that given
func (o *APIPreemptProxyGetPolicyRulesQueryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api preempt proxy get policy rules query o k response
func (o *APIPreemptProxyGetPolicyRulesQueryOK) Code() int {
	return 200
}

func (o *APIPreemptProxyGetPolicyRulesQueryOK) Error() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryOK  %+v", 200, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryOK) String() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryOK  %+v", 200, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryOK) GetPayload() *APIPreemptProxyGetPolicyRulesQueryOKBody {
	return o.Payload
}

func (o *APIPreemptProxyGetPolicyRulesQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(APIPreemptProxyGetPolicyRulesQueryOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyGetPolicyRulesQueryForbidden creates a APIPreemptProxyGetPolicyRulesQueryForbidden with default headers values
func NewAPIPreemptProxyGetPolicyRulesQueryForbidden() *APIPreemptProxyGetPolicyRulesQueryForbidden {
	return &APIPreemptProxyGetPolicyRulesQueryForbidden{}
}

/*
APIPreemptProxyGetPolicyRulesQueryForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type APIPreemptProxyGetPolicyRulesQueryForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy get policy rules query forbidden response has a 2xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy get policy rules query forbidden response has a 3xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy get policy rules query forbidden response has a 4xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this api preempt proxy get policy rules query forbidden response has a 5xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy get policy rules query forbidden response a status code equal to that given
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the api preempt proxy get policy rules query forbidden response
func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) Code() int {
	return 403
}

func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) Error() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryForbidden  %+v", 403, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) String() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryForbidden  %+v", 403, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyGetPolicyRulesQueryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyGetPolicyRulesQueryTooManyRequests creates a APIPreemptProxyGetPolicyRulesQueryTooManyRequests with default headers values
func NewAPIPreemptProxyGetPolicyRulesQueryTooManyRequests() *APIPreemptProxyGetPolicyRulesQueryTooManyRequests {
	return &APIPreemptProxyGetPolicyRulesQueryTooManyRequests{}
}

/*
APIPreemptProxyGetPolicyRulesQueryTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type APIPreemptProxyGetPolicyRulesQueryTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy get policy rules query too many requests response has a 2xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy get policy rules query too many requests response has a 3xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy get policy rules query too many requests response has a 4xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this api preempt proxy get policy rules query too many requests response has a 5xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy get policy rules query too many requests response a status code equal to that given
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the api preempt proxy get policy rules query too many requests response
func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) Code() int {
	return 429
}

func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryTooManyRequests  %+v", 429, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) String() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryTooManyRequests  %+v", 429, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyGetPolicyRulesQueryTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyGetPolicyRulesQueryInternalServerError creates a APIPreemptProxyGetPolicyRulesQueryInternalServerError with default headers values
func NewAPIPreemptProxyGetPolicyRulesQueryInternalServerError() *APIPreemptProxyGetPolicyRulesQueryInternalServerError {
	return &APIPreemptProxyGetPolicyRulesQueryInternalServerError{}
}

/*
APIPreemptProxyGetPolicyRulesQueryInternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type APIPreemptProxyGetPolicyRulesQueryInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy get policy rules query internal server error response has a 2xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy get policy rules query internal server error response has a 3xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy get policy rules query internal server error response has a 4xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this api preempt proxy get policy rules query internal server error response has a 5xx status code
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this api preempt proxy get policy rules query internal server error response a status code equal to that given
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the api preempt proxy get policy rules query internal server error response
func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) Code() int {
	return 500
}

func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) Error() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryInternalServerError  %+v", 500, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) String() string {
	return fmt.Sprintf("[GET /identity-protection/queries/policy-rules/v1][%d] apiPreemptProxyGetPolicyRulesQueryInternalServerError  %+v", 500, o.Payload)
}

func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyGetPolicyRulesQueryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
APIPreemptProxyGetPolicyRulesQueryOKBody API preempt proxy get policy rules query o k body
swagger:model APIPreemptProxyGetPolicyRulesQueryOKBody
*/
type APIPreemptProxyGetPolicyRulesQueryOKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this API preempt proxy get policy rules query o k body
func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this API preempt proxy get policy rules query o k body based on the context it is used
func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiPreemptProxyGetPolicyRulesQueryOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *APIPreemptProxyGetPolicyRulesQueryOKBody) UnmarshalBinary(b []byte) error {
	var res APIPreemptProxyGetPolicyRulesQueryOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
