// Code generated by go-swagger; DO NOT EDIT.

package identity_protection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// APIPreemptProxyPostPolicyRulesReader is a Reader for the APIPreemptProxyPostPolicyRules structure.
type APIPreemptProxyPostPolicyRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIPreemptProxyPostPolicyRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIPreemptProxyPostPolicyRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewAPIPreemptProxyPostPolicyRulesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewAPIPreemptProxyPostPolicyRulesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAPIPreemptProxyPostPolicyRulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /identity-protection/entities/policy-rules/v1] api.preempt.proxy.post.policy-rules", response, response.Code())
	}
}

// NewAPIPreemptProxyPostPolicyRulesOK creates a APIPreemptProxyPostPolicyRulesOK with default headers values
func NewAPIPreemptProxyPostPolicyRulesOK() *APIPreemptProxyPostPolicyRulesOK {
	return &APIPreemptProxyPostPolicyRulesOK{}
}

/*
APIPreemptProxyPostPolicyRulesOK describes a response with status code 200, with default header values.

OK
*/
type APIPreemptProxyPostPolicyRulesOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *APIPreemptProxyPostPolicyRulesOKBody
}

// IsSuccess returns true when this api preempt proxy post policy rules o k response has a 2xx status code
func (o *APIPreemptProxyPostPolicyRulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api preempt proxy post policy rules o k response has a 3xx status code
func (o *APIPreemptProxyPostPolicyRulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy post policy rules o k response has a 4xx status code
func (o *APIPreemptProxyPostPolicyRulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api preempt proxy post policy rules o k response has a 5xx status code
func (o *APIPreemptProxyPostPolicyRulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy post policy rules o k response a status code equal to that given
func (o *APIPreemptProxyPostPolicyRulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api preempt proxy post policy rules o k response
func (o *APIPreemptProxyPostPolicyRulesOK) Code() int {
	return 200
}

func (o *APIPreemptProxyPostPolicyRulesOK) Error() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesOK  %+v", 200, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesOK) String() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesOK  %+v", 200, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesOK) GetPayload() *APIPreemptProxyPostPolicyRulesOKBody {
	return o.Payload
}

func (o *APIPreemptProxyPostPolicyRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(APIPreemptProxyPostPolicyRulesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyPostPolicyRulesForbidden creates a APIPreemptProxyPostPolicyRulesForbidden with default headers values
func NewAPIPreemptProxyPostPolicyRulesForbidden() *APIPreemptProxyPostPolicyRulesForbidden {
	return &APIPreemptProxyPostPolicyRulesForbidden{}
}

/*
APIPreemptProxyPostPolicyRulesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type APIPreemptProxyPostPolicyRulesForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy post policy rules forbidden response has a 2xx status code
func (o *APIPreemptProxyPostPolicyRulesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy post policy rules forbidden response has a 3xx status code
func (o *APIPreemptProxyPostPolicyRulesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy post policy rules forbidden response has a 4xx status code
func (o *APIPreemptProxyPostPolicyRulesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this api preempt proxy post policy rules forbidden response has a 5xx status code
func (o *APIPreemptProxyPostPolicyRulesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy post policy rules forbidden response a status code equal to that given
func (o *APIPreemptProxyPostPolicyRulesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the api preempt proxy post policy rules forbidden response
func (o *APIPreemptProxyPostPolicyRulesForbidden) Code() int {
	return 403
}

func (o *APIPreemptProxyPostPolicyRulesForbidden) Error() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesForbidden  %+v", 403, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesForbidden) String() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesForbidden  %+v", 403, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyPostPolicyRulesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyPostPolicyRulesTooManyRequests creates a APIPreemptProxyPostPolicyRulesTooManyRequests with default headers values
func NewAPIPreemptProxyPostPolicyRulesTooManyRequests() *APIPreemptProxyPostPolicyRulesTooManyRequests {
	return &APIPreemptProxyPostPolicyRulesTooManyRequests{}
}

/*
APIPreemptProxyPostPolicyRulesTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type APIPreemptProxyPostPolicyRulesTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy post policy rules too many requests response has a 2xx status code
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy post policy rules too many requests response has a 3xx status code
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy post policy rules too many requests response has a 4xx status code
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this api preempt proxy post policy rules too many requests response has a 5xx status code
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this api preempt proxy post policy rules too many requests response a status code equal to that given
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the api preempt proxy post policy rules too many requests response
func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) Code() int {
	return 429
}

func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesTooManyRequests  %+v", 429, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) String() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesTooManyRequests  %+v", 429, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyPostPolicyRulesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIPreemptProxyPostPolicyRulesInternalServerError creates a APIPreemptProxyPostPolicyRulesInternalServerError with default headers values
func NewAPIPreemptProxyPostPolicyRulesInternalServerError() *APIPreemptProxyPostPolicyRulesInternalServerError {
	return &APIPreemptProxyPostPolicyRulesInternalServerError{}
}

/*
APIPreemptProxyPostPolicyRulesInternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type APIPreemptProxyPostPolicyRulesInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this api preempt proxy post policy rules internal server error response has a 2xx status code
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api preempt proxy post policy rules internal server error response has a 3xx status code
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api preempt proxy post policy rules internal server error response has a 4xx status code
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this api preempt proxy post policy rules internal server error response has a 5xx status code
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this api preempt proxy post policy rules internal server error response a status code equal to that given
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the api preempt proxy post policy rules internal server error response
func (o *APIPreemptProxyPostPolicyRulesInternalServerError) Code() int {
	return 500
}

func (o *APIPreemptProxyPostPolicyRulesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesInternalServerError) String() string {
	return fmt.Sprintf("[POST /identity-protection/entities/policy-rules/v1][%d] apiPreemptProxyPostPolicyRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *APIPreemptProxyPostPolicyRulesInternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *APIPreemptProxyPostPolicyRulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
APIPreemptProxyPostPolicyRulesOKBody API preempt proxy post policy rules o k body
swagger:model APIPreemptProxyPostPolicyRulesOKBody
*/
type APIPreemptProxyPostPolicyRulesOKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this API preempt proxy post policy rules o k body
func (o *APIPreemptProxyPostPolicyRulesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *APIPreemptProxyPostPolicyRulesOKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *APIPreemptProxyPostPolicyRulesOKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this API preempt proxy post policy rules o k body based on the context it is used
func (o *APIPreemptProxyPostPolicyRulesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *APIPreemptProxyPostPolicyRulesOKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *APIPreemptProxyPostPolicyRulesOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiPreemptProxyPostPolicyRulesOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *APIPreemptProxyPostPolicyRulesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *APIPreemptProxyPostPolicyRulesOKBody) UnmarshalBinary(b []byte) error {
	var res APIPreemptProxyPostPolicyRulesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
