// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainCredentials Represents credentials entity
//
// swagger:model domain.Credentials
type DomainCredentials struct {

	// Indicates if auto authorize scanners is enabled
	// Required: true
	AutoAuthorizeScanners *bool `json:"auto_authorize_scanners"`

	// Credential IDs associated with this scan
	// Required: true
	Ids []string `json:"ids"`
}

// Validate validates this domain credentials
func (m *DomainCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutoAuthorizeScanners(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainCredentials) validateAutoAuthorizeScanners(formats strfmt.Registry) error {

	if err := validate.Required("auto_authorize_scanners", "body", m.AutoAuthorizeScanners); err != nil {
		return err
	}

	return nil
}

func (m *DomainCredentials) validateIds(formats strfmt.Registry) error {

	if err := validate.Required("ids", "body", m.Ids); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this domain credentials based on context it is used
func (m *DomainCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DomainCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainCredentials) UnmarshalBinary(b []byte) error {
	var res DomainCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
