// Code generated by go-swagger; DO NOT EDIT.

package cloud_azure_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// CloudRegistrationAzureDeleteSuppressionsReader is a Reader for the CloudRegistrationAzureDeleteSuppressions structure.
type CloudRegistrationAzureDeleteSuppressionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CloudRegistrationAzureDeleteSuppressionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCloudRegistrationAzureDeleteSuppressionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCloudRegistrationAzureDeleteSuppressionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCloudRegistrationAzureDeleteSuppressionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCloudRegistrationAzureDeleteSuppressionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCloudRegistrationAzureDeleteSuppressionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1] cloud-registration-azure-delete-suppressions", response, response.Code())
	}
}

// NewCloudRegistrationAzureDeleteSuppressionsOK creates a CloudRegistrationAzureDeleteSuppressionsOK with default headers values
func NewCloudRegistrationAzureDeleteSuppressionsOK() *CloudRegistrationAzureDeleteSuppressionsOK {
	return &CloudRegistrationAzureDeleteSuppressionsOK{}
}

/*
CloudRegistrationAzureDeleteSuppressionsOK describes a response with status code 200, with default header values.

OK
*/
type CloudRegistrationAzureDeleteSuppressionsOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *CloudRegistrationAzureDeleteSuppressionsOKBody
}

// IsSuccess returns true when this cloud registration azure delete suppressions o k response has a 2xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cloud registration azure delete suppressions o k response has a 3xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud registration azure delete suppressions o k response has a 4xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cloud registration azure delete suppressions o k response has a 5xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cloud registration azure delete suppressions o k response a status code equal to that given
func (o *CloudRegistrationAzureDeleteSuppressionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the cloud registration azure delete suppressions o k response
func (o *CloudRegistrationAzureDeleteSuppressionsOK) Code() int {
	return 200
}

func (o *CloudRegistrationAzureDeleteSuppressionsOK) Error() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsOK  %+v", 200, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsOK) String() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsOK  %+v", 200, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsOK) GetPayload() *CloudRegistrationAzureDeleteSuppressionsOKBody {
	return o.Payload
}

func (o *CloudRegistrationAzureDeleteSuppressionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(CloudRegistrationAzureDeleteSuppressionsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudRegistrationAzureDeleteSuppressionsBadRequest creates a CloudRegistrationAzureDeleteSuppressionsBadRequest with default headers values
func NewCloudRegistrationAzureDeleteSuppressionsBadRequest() *CloudRegistrationAzureDeleteSuppressionsBadRequest {
	return &CloudRegistrationAzureDeleteSuppressionsBadRequest{}
}

/*
CloudRegistrationAzureDeleteSuppressionsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CloudRegistrationAzureDeleteSuppressionsBadRequest struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this cloud registration azure delete suppressions bad request response has a 2xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud registration azure delete suppressions bad request response has a 3xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud registration azure delete suppressions bad request response has a 4xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this cloud registration azure delete suppressions bad request response has a 5xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this cloud registration azure delete suppressions bad request response a status code equal to that given
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the cloud registration azure delete suppressions bad request response
func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) Code() int {
	return 400
}

func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsBadRequest  %+v", 400, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) String() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsBadRequest  %+v", 400, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *CloudRegistrationAzureDeleteSuppressionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudRegistrationAzureDeleteSuppressionsForbidden creates a CloudRegistrationAzureDeleteSuppressionsForbidden with default headers values
func NewCloudRegistrationAzureDeleteSuppressionsForbidden() *CloudRegistrationAzureDeleteSuppressionsForbidden {
	return &CloudRegistrationAzureDeleteSuppressionsForbidden{}
}

/*
CloudRegistrationAzureDeleteSuppressionsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CloudRegistrationAzureDeleteSuppressionsForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this cloud registration azure delete suppressions forbidden response has a 2xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud registration azure delete suppressions forbidden response has a 3xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud registration azure delete suppressions forbidden response has a 4xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this cloud registration azure delete suppressions forbidden response has a 5xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this cloud registration azure delete suppressions forbidden response a status code equal to that given
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the cloud registration azure delete suppressions forbidden response
func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) Code() int {
	return 403
}

func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsForbidden  %+v", 403, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) String() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsForbidden  %+v", 403, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *CloudRegistrationAzureDeleteSuppressionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudRegistrationAzureDeleteSuppressionsTooManyRequests creates a CloudRegistrationAzureDeleteSuppressionsTooManyRequests with default headers values
func NewCloudRegistrationAzureDeleteSuppressionsTooManyRequests() *CloudRegistrationAzureDeleteSuppressionsTooManyRequests {
	return &CloudRegistrationAzureDeleteSuppressionsTooManyRequests{}
}

/*
CloudRegistrationAzureDeleteSuppressionsTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type CloudRegistrationAzureDeleteSuppressionsTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this cloud registration azure delete suppressions too many requests response has a 2xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud registration azure delete suppressions too many requests response has a 3xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud registration azure delete suppressions too many requests response has a 4xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this cloud registration azure delete suppressions too many requests response has a 5xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this cloud registration azure delete suppressions too many requests response a status code equal to that given
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the cloud registration azure delete suppressions too many requests response
func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) Code() int {
	return 429
}

func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsTooManyRequests  %+v", 429, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) String() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsTooManyRequests  %+v", 429, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CloudRegistrationAzureDeleteSuppressionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudRegistrationAzureDeleteSuppressionsInternalServerError creates a CloudRegistrationAzureDeleteSuppressionsInternalServerError with default headers values
func NewCloudRegistrationAzureDeleteSuppressionsInternalServerError() *CloudRegistrationAzureDeleteSuppressionsInternalServerError {
	return &CloudRegistrationAzureDeleteSuppressionsInternalServerError{}
}

/*
CloudRegistrationAzureDeleteSuppressionsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CloudRegistrationAzureDeleteSuppressionsInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaspecResponseFields
}

// IsSuccess returns true when this cloud registration azure delete suppressions internal server error response has a 2xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud registration azure delete suppressions internal server error response has a 3xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud registration azure delete suppressions internal server error response has a 4xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this cloud registration azure delete suppressions internal server error response has a 5xx status code
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this cloud registration azure delete suppressions internal server error response a status code equal to that given
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the cloud registration azure delete suppressions internal server error response
func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) Code() int {
	return 500
}

func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsInternalServerError  %+v", 500, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /cloud-security-registration-azure/entities/issue-suppressions/v1][%d] cloudRegistrationAzureDeleteSuppressionsInternalServerError  %+v", 500, o.Payload)
}

func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) GetPayload() *models.MsaspecResponseFields {
	return o.Payload
}

func (o *CloudRegistrationAzureDeleteSuppressionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaspecResponseFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CloudRegistrationAzureDeleteSuppressionsOKBody cloud registration azure delete suppressions o k body
swagger:model CloudRegistrationAzureDeleteSuppressionsOKBody
*/
type CloudRegistrationAzureDeleteSuppressionsOKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this cloud registration azure delete suppressions o k body
func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this cloud registration azure delete suppressions o k body based on the context it is used
func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cloudRegistrationAzureDeleteSuppressionsOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CloudRegistrationAzureDeleteSuppressionsOKBody) UnmarshalBinary(b []byte) error {
	var res CloudRegistrationAzureDeleteSuppressionsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
