// Code generated by go-swagger; DO NOT EDIT.

package quick_scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// GetScansAggregatesReader is a Reader for the GetScansAggregates structure.
type GetScansAggregatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScansAggregatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScansAggregatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetScansAggregatesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetScansAggregatesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetScansAggregatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /scanner/aggregates/scans/GET/v1] GetScansAggregates", response, response.Code())
	}
}

// NewGetScansAggregatesOK creates a GetScansAggregatesOK with default headers values
func NewGetScansAggregatesOK() *GetScansAggregatesOK {
	return &GetScansAggregatesOK{}
}

/*
GetScansAggregatesOK describes a response with status code 200, with default header values.

OK
*/
type GetScansAggregatesOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *GetScansAggregatesOKBody
}

// IsSuccess returns true when this get scans aggregates o k response has a 2xx status code
func (o *GetScansAggregatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get scans aggregates o k response has a 3xx status code
func (o *GetScansAggregatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get scans aggregates o k response has a 4xx status code
func (o *GetScansAggregatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get scans aggregates o k response has a 5xx status code
func (o *GetScansAggregatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get scans aggregates o k response a status code equal to that given
func (o *GetScansAggregatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get scans aggregates o k response
func (o *GetScansAggregatesOK) Code() int {
	return 200
}

func (o *GetScansAggregatesOK) Error() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesOK  %+v", 200, o.Payload)
}

func (o *GetScansAggregatesOK) String() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesOK  %+v", 200, o.Payload)
}

func (o *GetScansAggregatesOK) GetPayload() *GetScansAggregatesOKBody {
	return o.Payload
}

func (o *GetScansAggregatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(GetScansAggregatesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScansAggregatesForbidden creates a GetScansAggregatesForbidden with default headers values
func NewGetScansAggregatesForbidden() *GetScansAggregatesForbidden {
	return &GetScansAggregatesForbidden{}
}

/*
GetScansAggregatesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetScansAggregatesForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get scans aggregates forbidden response has a 2xx status code
func (o *GetScansAggregatesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get scans aggregates forbidden response has a 3xx status code
func (o *GetScansAggregatesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get scans aggregates forbidden response has a 4xx status code
func (o *GetScansAggregatesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get scans aggregates forbidden response has a 5xx status code
func (o *GetScansAggregatesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get scans aggregates forbidden response a status code equal to that given
func (o *GetScansAggregatesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get scans aggregates forbidden response
func (o *GetScansAggregatesForbidden) Code() int {
	return 403
}

func (o *GetScansAggregatesForbidden) Error() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesForbidden  %+v", 403, o.Payload)
}

func (o *GetScansAggregatesForbidden) String() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesForbidden  %+v", 403, o.Payload)
}

func (o *GetScansAggregatesForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetScansAggregatesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScansAggregatesTooManyRequests creates a GetScansAggregatesTooManyRequests with default headers values
func NewGetScansAggregatesTooManyRequests() *GetScansAggregatesTooManyRequests {
	return &GetScansAggregatesTooManyRequests{}
}

/*
GetScansAggregatesTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetScansAggregatesTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get scans aggregates too many requests response has a 2xx status code
func (o *GetScansAggregatesTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get scans aggregates too many requests response has a 3xx status code
func (o *GetScansAggregatesTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get scans aggregates too many requests response has a 4xx status code
func (o *GetScansAggregatesTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get scans aggregates too many requests response has a 5xx status code
func (o *GetScansAggregatesTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get scans aggregates too many requests response a status code equal to that given
func (o *GetScansAggregatesTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get scans aggregates too many requests response
func (o *GetScansAggregatesTooManyRequests) Code() int {
	return 429
}

func (o *GetScansAggregatesTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetScansAggregatesTooManyRequests) String() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetScansAggregatesTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetScansAggregatesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScansAggregatesInternalServerError creates a GetScansAggregatesInternalServerError with default headers values
func NewGetScansAggregatesInternalServerError() *GetScansAggregatesInternalServerError {
	return &GetScansAggregatesInternalServerError{}
}

/*
GetScansAggregatesInternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type GetScansAggregatesInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get scans aggregates internal server error response has a 2xx status code
func (o *GetScansAggregatesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get scans aggregates internal server error response has a 3xx status code
func (o *GetScansAggregatesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get scans aggregates internal server error response has a 4xx status code
func (o *GetScansAggregatesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get scans aggregates internal server error response has a 5xx status code
func (o *GetScansAggregatesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get scans aggregates internal server error response a status code equal to that given
func (o *GetScansAggregatesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get scans aggregates internal server error response
func (o *GetScansAggregatesInternalServerError) Code() int {
	return 500
}

func (o *GetScansAggregatesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetScansAggregatesInternalServerError) String() string {
	return fmt.Sprintf("[POST /scanner/aggregates/scans/GET/v1][%d] getScansAggregatesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetScansAggregatesInternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetScansAggregatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetScansAggregatesOKBody get scans aggregates o k body
swagger:model GetScansAggregatesOKBody
*/
type GetScansAggregatesOKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this get scans aggregates o k body
func (o *GetScansAggregatesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScansAggregatesOKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getScansAggregatesOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getScansAggregatesOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetScansAggregatesOKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getScansAggregatesOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getScansAggregatesOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get scans aggregates o k body based on the context it is used
func (o *GetScansAggregatesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScansAggregatesOKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getScansAggregatesOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getScansAggregatesOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetScansAggregatesOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getScansAggregatesOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getScansAggregatesOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetScansAggregatesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScansAggregatesOKBody) UnmarshalBinary(b []byte) error {
	var res GetScansAggregatesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
