// Code generated by go-swagger; DO NOT EDIT.

package ioa_exclusions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// SsIoaExclusionsGetReportsV2Reader is a Reader for the SsIoaExclusionsGetReportsV2 structure.
type SsIoaExclusionsGetReportsV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SsIoaExclusionsGetReportsV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSsIoaExclusionsGetReportsV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSsIoaExclusionsGetReportsV2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSsIoaExclusionsGetReportsV2TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSsIoaExclusionsGetReportsV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2] ss-ioa-exclusions.get-reports.v2", response, response.Code())
	}
}

// NewSsIoaExclusionsGetReportsV2OK creates a SsIoaExclusionsGetReportsV2OK with default headers values
func NewSsIoaExclusionsGetReportsV2OK() *SsIoaExclusionsGetReportsV2OK {
	return &SsIoaExclusionsGetReportsV2OK{}
}

/*
SsIoaExclusionsGetReportsV2OK describes a response with status code 200, with default header values.

OK
*/
type SsIoaExclusionsGetReportsV2OK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *SsIoaExclusionsGetReportsV2OKBody
}

// IsSuccess returns true when this ss ioa exclusions get reports v2 o k response has a 2xx status code
func (o *SsIoaExclusionsGetReportsV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ss ioa exclusions get reports v2 o k response has a 3xx status code
func (o *SsIoaExclusionsGetReportsV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ss ioa exclusions get reports v2 o k response has a 4xx status code
func (o *SsIoaExclusionsGetReportsV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ss ioa exclusions get reports v2 o k response has a 5xx status code
func (o *SsIoaExclusionsGetReportsV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this ss ioa exclusions get reports v2 o k response a status code equal to that given
func (o *SsIoaExclusionsGetReportsV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ss ioa exclusions get reports v2 o k response
func (o *SsIoaExclusionsGetReportsV2OK) Code() int {
	return 200
}

func (o *SsIoaExclusionsGetReportsV2OK) Error() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2OK  %+v", 200, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2OK) String() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2OK  %+v", 200, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2OK) GetPayload() *SsIoaExclusionsGetReportsV2OKBody {
	return o.Payload
}

func (o *SsIoaExclusionsGetReportsV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(SsIoaExclusionsGetReportsV2OKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSsIoaExclusionsGetReportsV2Forbidden creates a SsIoaExclusionsGetReportsV2Forbidden with default headers values
func NewSsIoaExclusionsGetReportsV2Forbidden() *SsIoaExclusionsGetReportsV2Forbidden {
	return &SsIoaExclusionsGetReportsV2Forbidden{}
}

/*
SsIoaExclusionsGetReportsV2Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SsIoaExclusionsGetReportsV2Forbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this ss ioa exclusions get reports v2 forbidden response has a 2xx status code
func (o *SsIoaExclusionsGetReportsV2Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ss ioa exclusions get reports v2 forbidden response has a 3xx status code
func (o *SsIoaExclusionsGetReportsV2Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ss ioa exclusions get reports v2 forbidden response has a 4xx status code
func (o *SsIoaExclusionsGetReportsV2Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this ss ioa exclusions get reports v2 forbidden response has a 5xx status code
func (o *SsIoaExclusionsGetReportsV2Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this ss ioa exclusions get reports v2 forbidden response a status code equal to that given
func (o *SsIoaExclusionsGetReportsV2Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the ss ioa exclusions get reports v2 forbidden response
func (o *SsIoaExclusionsGetReportsV2Forbidden) Code() int {
	return 403
}

func (o *SsIoaExclusionsGetReportsV2Forbidden) Error() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2Forbidden  %+v", 403, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2Forbidden) String() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2Forbidden  %+v", 403, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2Forbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *SsIoaExclusionsGetReportsV2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSsIoaExclusionsGetReportsV2TooManyRequests creates a SsIoaExclusionsGetReportsV2TooManyRequests with default headers values
func NewSsIoaExclusionsGetReportsV2TooManyRequests() *SsIoaExclusionsGetReportsV2TooManyRequests {
	return &SsIoaExclusionsGetReportsV2TooManyRequests{}
}

/*
SsIoaExclusionsGetReportsV2TooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type SsIoaExclusionsGetReportsV2TooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this ss ioa exclusions get reports v2 too many requests response has a 2xx status code
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ss ioa exclusions get reports v2 too many requests response has a 3xx status code
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ss ioa exclusions get reports v2 too many requests response has a 4xx status code
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this ss ioa exclusions get reports v2 too many requests response has a 5xx status code
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this ss ioa exclusions get reports v2 too many requests response a status code equal to that given
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the ss ioa exclusions get reports v2 too many requests response
func (o *SsIoaExclusionsGetReportsV2TooManyRequests) Code() int {
	return 429
}

func (o *SsIoaExclusionsGetReportsV2TooManyRequests) Error() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2TooManyRequests  %+v", 429, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2TooManyRequests) String() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2TooManyRequests  %+v", 429, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2TooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *SsIoaExclusionsGetReportsV2TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSsIoaExclusionsGetReportsV2InternalServerError creates a SsIoaExclusionsGetReportsV2InternalServerError with default headers values
func NewSsIoaExclusionsGetReportsV2InternalServerError() *SsIoaExclusionsGetReportsV2InternalServerError {
	return &SsIoaExclusionsGetReportsV2InternalServerError{}
}

/*
SsIoaExclusionsGetReportsV2InternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type SsIoaExclusionsGetReportsV2InternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this ss ioa exclusions get reports v2 internal server error response has a 2xx status code
func (o *SsIoaExclusionsGetReportsV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ss ioa exclusions get reports v2 internal server error response has a 3xx status code
func (o *SsIoaExclusionsGetReportsV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ss ioa exclusions get reports v2 internal server error response has a 4xx status code
func (o *SsIoaExclusionsGetReportsV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this ss ioa exclusions get reports v2 internal server error response has a 5xx status code
func (o *SsIoaExclusionsGetReportsV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this ss ioa exclusions get reports v2 internal server error response a status code equal to that given
func (o *SsIoaExclusionsGetReportsV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the ss ioa exclusions get reports v2 internal server error response
func (o *SsIoaExclusionsGetReportsV2InternalServerError) Code() int {
	return 500
}

func (o *SsIoaExclusionsGetReportsV2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2InternalServerError  %+v", 500, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2InternalServerError) String() string {
	return fmt.Sprintf("[POST /exclusions/entities/ss-ioa-exclusions/reports/v2][%d] ssIoaExclusionsGetReportsV2InternalServerError  %+v", 500, o.Payload)
}

func (o *SsIoaExclusionsGetReportsV2InternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *SsIoaExclusionsGetReportsV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
SsIoaExclusionsGetReportsV2OKBody ss ioa exclusions get reports v2 o k body
swagger:model SsIoaExclusionsGetReportsV2OKBody
*/
type SsIoaExclusionsGetReportsV2OKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this ss ioa exclusions get reports v2 o k body
func (o *SsIoaExclusionsGetReportsV2OKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SsIoaExclusionsGetReportsV2OKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *SsIoaExclusionsGetReportsV2OKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ss ioa exclusions get reports v2 o k body based on the context it is used
func (o *SsIoaExclusionsGetReportsV2OKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SsIoaExclusionsGetReportsV2OKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *SsIoaExclusionsGetReportsV2OKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ssIoaExclusionsGetReportsV2OK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SsIoaExclusionsGetReportsV2OKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SsIoaExclusionsGetReportsV2OKBody) UnmarshalBinary(b []byte) error {
	var res SsIoaExclusionsGetReportsV2OKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
