// Code generated by go-swagger; DO NOT EDIT.

package threatgraph

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// CombinedSummaryGetReader is a Reader for the CombinedSummaryGet structure.
type CombinedSummaryGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CombinedSummaryGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCombinedSummaryGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCombinedSummaryGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCombinedSummaryGetTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCombinedSummaryGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /threatgraph/combined/{vertex-type}/summary/v1] combined_summary_get", response, response.Code())
	}
}

// NewCombinedSummaryGetOK creates a CombinedSummaryGetOK with default headers values
func NewCombinedSummaryGetOK() *CombinedSummaryGetOK {
	return &CombinedSummaryGetOK{}
}

/*
CombinedSummaryGetOK describes a response with status code 200, with default header values.

OK
*/
type CombinedSummaryGetOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *CombinedSummaryGetOKBody
}

// IsSuccess returns true when this combined summary get o k response has a 2xx status code
func (o *CombinedSummaryGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this combined summary get o k response has a 3xx status code
func (o *CombinedSummaryGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this combined summary get o k response has a 4xx status code
func (o *CombinedSummaryGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this combined summary get o k response has a 5xx status code
func (o *CombinedSummaryGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this combined summary get o k response a status code equal to that given
func (o *CombinedSummaryGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the combined summary get o k response
func (o *CombinedSummaryGetOK) Code() int {
	return 200
}

func (o *CombinedSummaryGetOK) Error() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetOK  %+v", 200, o.Payload)
}

func (o *CombinedSummaryGetOK) String() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetOK  %+v", 200, o.Payload)
}

func (o *CombinedSummaryGetOK) GetPayload() *CombinedSummaryGetOKBody {
	return o.Payload
}

func (o *CombinedSummaryGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(CombinedSummaryGetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCombinedSummaryGetForbidden creates a CombinedSummaryGetForbidden with default headers values
func NewCombinedSummaryGetForbidden() *CombinedSummaryGetForbidden {
	return &CombinedSummaryGetForbidden{}
}

/*
CombinedSummaryGetForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CombinedSummaryGetForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this combined summary get forbidden response has a 2xx status code
func (o *CombinedSummaryGetForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this combined summary get forbidden response has a 3xx status code
func (o *CombinedSummaryGetForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this combined summary get forbidden response has a 4xx status code
func (o *CombinedSummaryGetForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this combined summary get forbidden response has a 5xx status code
func (o *CombinedSummaryGetForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this combined summary get forbidden response a status code equal to that given
func (o *CombinedSummaryGetForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the combined summary get forbidden response
func (o *CombinedSummaryGetForbidden) Code() int {
	return 403
}

func (o *CombinedSummaryGetForbidden) Error() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetForbidden  %+v", 403, o.Payload)
}

func (o *CombinedSummaryGetForbidden) String() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetForbidden  %+v", 403, o.Payload)
}

func (o *CombinedSummaryGetForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CombinedSummaryGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCombinedSummaryGetTooManyRequests creates a CombinedSummaryGetTooManyRequests with default headers values
func NewCombinedSummaryGetTooManyRequests() *CombinedSummaryGetTooManyRequests {
	return &CombinedSummaryGetTooManyRequests{}
}

/*
CombinedSummaryGetTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type CombinedSummaryGetTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this combined summary get too many requests response has a 2xx status code
func (o *CombinedSummaryGetTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this combined summary get too many requests response has a 3xx status code
func (o *CombinedSummaryGetTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this combined summary get too many requests response has a 4xx status code
func (o *CombinedSummaryGetTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this combined summary get too many requests response has a 5xx status code
func (o *CombinedSummaryGetTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this combined summary get too many requests response a status code equal to that given
func (o *CombinedSummaryGetTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the combined summary get too many requests response
func (o *CombinedSummaryGetTooManyRequests) Code() int {
	return 429
}

func (o *CombinedSummaryGetTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetTooManyRequests  %+v", 429, o.Payload)
}

func (o *CombinedSummaryGetTooManyRequests) String() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetTooManyRequests  %+v", 429, o.Payload)
}

func (o *CombinedSummaryGetTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CombinedSummaryGetTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCombinedSummaryGetInternalServerError creates a CombinedSummaryGetInternalServerError with default headers values
func NewCombinedSummaryGetInternalServerError() *CombinedSummaryGetInternalServerError {
	return &CombinedSummaryGetInternalServerError{}
}

/*
CombinedSummaryGetInternalServerError describes a response with status code 500, with default header values.

Unexpected Error
*/
type CombinedSummaryGetInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this combined summary get internal server error response has a 2xx status code
func (o *CombinedSummaryGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this combined summary get internal server error response has a 3xx status code
func (o *CombinedSummaryGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this combined summary get internal server error response has a 4xx status code
func (o *CombinedSummaryGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this combined summary get internal server error response has a 5xx status code
func (o *CombinedSummaryGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this combined summary get internal server error response a status code equal to that given
func (o *CombinedSummaryGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the combined summary get internal server error response
func (o *CombinedSummaryGetInternalServerError) Code() int {
	return 500
}

func (o *CombinedSummaryGetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetInternalServerError  %+v", 500, o.Payload)
}

func (o *CombinedSummaryGetInternalServerError) String() string {
	return fmt.Sprintf("[GET /threatgraph/combined/{vertex-type}/summary/v1][%d] combinedSummaryGetInternalServerError  %+v", 500, o.Payload)
}

func (o *CombinedSummaryGetInternalServerError) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CombinedSummaryGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CombinedSummaryGetOKBody combined summary get o k body
swagger:model CombinedSummaryGetOKBody
*/
type CombinedSummaryGetOKBody struct {

	// errors
	Errors []*models.MsaAPIError `json:"errors"`

	// meta
	Meta *models.MsaMetaInfo `json:"meta,omitempty"`

	// resources
	Resources []interface{} `json:"resources"`
}

// Validate validates this combined summary get o k body
func (o *CombinedSummaryGetOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CombinedSummaryGetOKBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("combinedSummaryGetOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("combinedSummaryGetOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CombinedSummaryGetOKBody) validateMeta(formats strfmt.Registry) error {
	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("combinedSummaryGetOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("combinedSummaryGetOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this combined summary get o k body based on the context it is used
func (o *CombinedSummaryGetOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CombinedSummaryGetOKBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("combinedSummaryGetOK" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("combinedSummaryGetOK" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CombinedSummaryGetOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("combinedSummaryGetOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("combinedSummaryGetOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CombinedSummaryGetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CombinedSummaryGetOKBody) UnmarshalBinary(b []byte) error {
	var res CombinedSummaryGetOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
